module.exports = {
  layout : {
    pageShell : 'flex flex-1 flex-col w-full min-h-0',
    mainMax : 'flex-1 pt-40 pb-24 px-8 lg:px-12 max-w-[1440px] mx-auto w-full',
    mainHome : 'flex-1 w-full max-w-[1440px] mx-auto pt-40 px-12',
    grid12 : 'grid grid-cols-1 lg:grid-cols-12 gap-24',
    contentCol : 'lg:col-span-9',
    contentArticle : 'lg:col-span-9 max-w-2xl',
  },
  sidebar : {
    aside : 'hidden lg:block lg:col-span-3',
    sticky : 'sticky top-40 flex flex-col gap-8',
    card : 'p-8 bg-surface-container-low border border-outline-variant/20',
    cardTitle : 'font-serif italic text-xl text-on-surface mb-2',
    cardSubtitle : 'font-mono text-[10px] tracking-widest text-on-surface-variant uppercase mb-6',
    navStack : 'flex flex-col gap-4',
    navLinkBase : 'font-serif italic text-base transition-colors',
    navDot : 'w-1.5 h-1.5 bg-secondary shrink-0',
  },
  breadcrumb : {
    link : 'hover:text-secondary transition-colors',
    tagLink : 'hover:text-secondary transition-colors text-outline-variant',
    sep : 'w-4 h-px bg-outline-variant/30',
  },
  grid : {
    cards : 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8',
    albumPhotos : 'grid grid-cols-2 md:grid-cols-3 gap-3 md:gap-4',
  },
  prose : {
    maxMb : 'prose max-w-2xl mb-12',
  },
  topNav : {
    bar : 'fixed top-0 w-full z-50 bg-background/80 backdrop-blur-xl border-b border-outline-variant/10',
    inner : 'grid grid-cols-[1fr_auto_1fr] items-center px-12 py-6 w-full max-w-[1920px] mx-auto gap-4',
    home : 'text-2xl text-on-surface justify-self-start min-w-0',
    center : 'hidden md:flex justify-center items-center gap-12 flex-wrap justify-self-center',
    primaryBase : 'font-serif italic text-lg transition-colors duration-300',
    primaryActive : 'text-on-surface border-b border-primary pb-1',
    primaryIdle : 'text-outline-variant font-medium hover:text-secondary',
    external : 'text-outline-variant font-medium hover:text-secondary transition-colors duration-300 font-serif italic text-lg',
    actions : 'flex items-center gap-6 justify-self-end',
    iconLink : 'text-primary hover:text-secondary transition-colors scale-95 duration-200',
  },
  footer : {
    bar : 'bg-background w-full py-24 px-12 border-t border-outline-variant/10',
    inner : 'flex flex-col md:flex-row justify-between items-center w-full max-w-[1440px] mx-auto opacity-80 hover:opacity-100 transition-opacity',
    brandCol : 'mb-12 md:mb-0 text-center md:text-left',
    wordmarkWrap : 'text-2xl text-on-surface mb-4',
    copyright : 'font-mono text-xs tracking-widest text-outline-variant',
    linksRow : 'flex flex-wrap justify-center gap-12',
    link : 'font-mono text-xs tracking-widest text-outline-variant hover:text-on-surface transition-colors',
    linkUnderline : 'font-mono text-xs tracking-widest text-outline-variant hover:text-on-surface transition-colors underline',
  },
  home : {
    heroStage : 'relative mb-32 flex min-h-[calc(100dvh-10rem)] max-w-5xl flex-col justify-center',
    heroTitle : 'font-headline italic text-7xl md:text-8xl tracking-tight leading-[1.1] mb-10 text-on-surface',
    heroDesc : 'font-headline italic text-2xl text-on-surface-variant/80 max-w-2xl leading-relaxed',
    scrollHint : 'pointer-events-none absolute bottom-6 left-1/2 flex -translate-x-1/2 flex-col items-center gap-1 text-on-surface-variant/50',
  },
  featured : {
    article : 'w-full group mb-16 md:mb-20',
    thumbLink : 'block aspect-[16/9] overflow-hidden bg-surface-container-low mb-8 relative focus:outline-none focus-visible:ring-2 focus-visible:ring-secondary',
    img : 'w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105 opacity-80 group-hover:opacity-100',
    tagWrap : 'absolute top-8 left-8 pointer-events-none',
    tagPill : 'px-4 py-1.5 border border-primary text-primary font-label text-[10px] tracking-[0.3em] uppercase bg-background/40 backdrop-blur-md',
    body : 'max-w-3xl',
    metaRow : 'flex items-center gap-6 mb-6 font-label text-[10px] text-on-surface-variant tracking-[0.2em] uppercase',
    metaDivider : 'w-8 h-[1px] bg-outline-variant/30',
    title : 'font-headline italic text-5xl md:text-6xl mb-6 group-hover:text-secondary transition-colors duration-500 leading-tight',
    titleLink : 'hover:text-secondary',
    excerpt : 'font-body text-lg text-on-surface-variant/70 leading-relaxed',
  },
  previewCard : {
    article : 'group',
    link : 'block text-inherit no-underline',
    thumbBox : 'aspect-[4/3] overflow-hidden bg-surface-container-low mb-6',
    thumbPlaceholder : 'aspect-[4/3] bg-surface-container-low mb-6',
    img : 'w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105 opacity-60 group-hover:opacity-100',
    tag : 'font-label text-[9px] tracking-[0.3em] uppercase text-secondary mb-4 block',
    title : 'font-headline italic text-2xl mb-4 group-hover:text-primary transition-colors duration-500',
    excerpt : 'font-body text-sm text-on-surface-variant/70 line-clamp-2 leading-relaxed',
    footerMeta : 'mt-6 font-label text-[9px] text-outline tracking-[0.2em] uppercase',
  },
  postList : {
    pageTitle : 'font-headline italic text-5xl md:text-6xl text-on-surface mb-4',
    emptyText : 'text-on-surface-variant',
  },
  post : {
    breadcrumbNav : 'flex flex-wrap items-center gap-4 mb-16 text-[9px] font-mono uppercase tracking-[0.4em] text-outline-variant',
    sidebar : {
      metaCol : 'flex flex-col gap-4',
      createdLabel : 'font-mono text-[9px] tracking-[0.3em] uppercase text-outline-variant',
      dateLine : 'font-serif text-sm italic text-primary',
    },
    hero : {
      wrap : 'not-prose mb-12 aspect-[16/9] w-full overflow-hidden bg-surface-container-low',
      img : 'w-full h-full object-cover',
    },
    byline : {
      row : 'flex items-center gap-6 mb-16 not-prose',
      avatarWrap : 'flex items-center gap-3',
      avatarBox : 'w-10 h-10 bg-surface-container-highest overflow-hidden grayscale',
      avatarImg : 'w-full h-full object-cover opacity-80',
      textCol : 'flex flex-col',
      divider : 'h-8 w-px bg-outline-variant/20',
      metaLabel : 'font-mono text-[9px] tracking-widest text-outline-variant uppercase',
      authorName : 'font-serif italic text-sm text-on-surface',
      readingValue : 'font-serif italic text-sm text-primary',
    },
    related : {
      section : 'mt-32 pt-16 border-t border-outline-variant/20 not-prose',
      title : 'font-serif italic text-3xl text-on-surface mb-12',
      grid : 'grid grid-cols-1 md:grid-cols-2 gap-12',
      card : 'group cursor-pointer',
      link : 'block text-inherit no-underline',
      thumb : 'aspect-[4/5] bg-surface-container-low overflow-hidden mb-6 relative',
      img : 'w-full h-full object-cover grayscale opacity-60 group-hover:opacity-100 group-hover:scale-105 transition-all duration-1000',
      overlay : 'absolute inset-0 bg-background/40 group-hover:bg-transparent transition-colors',
      tag : 'font-mono text-[9px] tracking-[0.4em] uppercase text-secondary mb-3 block',
      cardTitle : 'font-serif italic text-xl text-on-surface leading-tight group-hover:text-secondary transition-colors',
    },
  },
  album : {
    breadcrumbNav : 'flex flex-wrap items-center gap-4 mb-10 text-[9px] font-mono uppercase tracking-[0.4em] text-outline-variant',
    pageTitle : 'font-headline italic text-5xl md:text-6xl text-on-surface mb-6',
    dateLine : 'font-label text-[10px] text-on-surface-variant tracking-[0.2em] uppercase mb-10',
    lightboxBtn : 'js-album-lightbox-open group relative aspect-square overflow-hidden bg-surface-container-low border-0 p-0 cursor-pointer w-full text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-secondary',
    thumbImg : 'w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 opacity-90 group-hover:opacity-100',
  },
};
